### PR TITLE
owm2ffmap.py: Adjust the boundary box for fetching node-data from owm.

### PR DESCRIPTION
**Pull request by akira25**
This commit will include some parts of East Brandenburg into the map. Main goal is to include the nodes of Fürstenwalde, which currently has not the resources to host an own independent map.

@sarumpaet Is that okay for you? I'd like to have this merged rather quickly, as we currently have no map, we can look our nodes after.

### CODE REVIEW

**Comment by SvenRoederer** [comment]
As far as I got it the OWM-setup is down completely, so the owm2ffmap-py will not work anyway. 

> dig api.openwifimap.net 
> ;; QUESTION SECTION:
> ;api.openwifimap.net.           IN      A
>
> ;; ANSWER SECTION:
> api.openwifimap.net.    597     IN      CNAME   util.berlin.freifunk.net.
> util.berlin.freifunk.net. 1376  IN      A       77.87.50.18

**Comment by SvenRoederer** [comment]
@Akira25 regarding a map for Fürstenwalde: As you already have setup a community-profile it's probably more easy to setup a separate instance for you / by you? Or modify https://github.com/freifunk-berlin/util.berlin.freifunk.net/blob/master/www/update_node.php to put the data for you into a separate folder for "map.fuewa.freifunk.net". Pushing your node-data to a separate host "utils.fuewa.freifunk.net" should make detection really easy.

**Comment by sarumpaet** [comment]
@SvenRoederer owm2ffmap works even if OWM is down since 97b0447 . Previously it only listed the nodes that POSTed their data to util.berlin then but since a few days openwifimap.net points to the util server as well so we should see all nodes in Hopglass now.

@Akira25 We can try to find another solution at some point but merging this for now.

**Comment by SvenRoederer** [comment]
@sarumpaet  sure, the data are stored locally since some time. But I wonder how the "owm2ffmap" can request the URL with the bounding_box parameter (https://github.com/freifunk-berlin/hopglass.berlin.freifunk.net/blob/3a9279be7dd67b04e43d7b06b5f23306d75fe316/owm2ffmap/owm2ffmap.py#L57)? The host currently point to util.berlin.freifunk.net and there seems to be no script "view_nodes_spatial". I also thought doing the geo-query is a special thing of the OWM-database.

**Comment by sarumpaet** [comment]
That code isn't used anymore. The change is because of the check at https://github.com/freifunk-berlin/hopglass.berlin.freifunk.net/blob/3a9279be7dd67b04e43d7b06b5f23306d75fe316/owm2ffmap/owm2ffmap.py#L68 .

**Comment by SvenRoederer** [comment]
Thanks, I'm back on board :-)

**Pull request merged**
